### ISSUE TITLE
トップページのSPARQLリンク修正

### ISSUE THREAD

**Issue by okbp** [rdfportal/rdfportal.github.io#3]
トップページ左バーの[SPARQL]のリンクのURLが変わったので修正をお願いします。
/sparql => /primary/sparql
https://rdfportal.org/primary/sparql

**Comment by penqe** [comment]
@okbp 対応しました
https://github.com/rdfportal/rdfportal.github.io/commit/49d8c0127c6145a4948d651847ece1d047623272

**Comment by okbp** [comment]
@penqe ありがとうございます。反映して確認しました。
